myapp_oauth_server_auth_login:
  path: /oauth/v2/auth/login
  defaults: { _controller: AppBundle:Connect:enter }

myapp_oauth_server_auth_login_check:
  path: /oauth/v2/auth/login_check
  defaults: { _controller: AppBundle:Security:check }